server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.1.53:8848


service-url:
  nacos-user-service: http://nacos-payment-provider